# Default values for elastic.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

esMajorVersion: ""

image: docker.elastic.co/elasticsearch/elasticsearch
imagePullPolicy: IfNotPresent

esJavaOpts: "-Xmx256m -Xms256m"

networkHost: "0.0.0.0"

protocol: http
httpPort: 9200
transportPort: 9300

nameOverride: ""
fullnameOverride: ""

serviceType: ClusterIP

resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 512Mi

esConfig:
  elasticsearchConf:
    xpack.monitoring.collection.enabled: true
    network.host: "0.0.0.0"
    node.master: true
    node.data: true

global:
  imageTag: 7.3.0
