# Default values for kibana.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image: docker.elastic.co/kibana/kibana
imagePullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

serviceType: ClusterIP
httpPort: 5601

ingressHosts:
- host: kibana.krystal.local
  paths: [ '/' ]

resources:
  limits:
    memory: 1024M
  requests:
    memory: 1024M
