apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  elasticsearch.yml: |
    cluster.name: {{ .Release.Name }}
    http.port: {{ .Values.httpPort }}
    discovery.type: single-node
{{- range $key, $value := .Values.esConfig.elasticsearchConf }}
    {{ $key }}: {{ $value }}
{{- end }}
  jvm.options: |-
    {{ .Files.Get "files/jvm.options" | nindent 4 }}
