# Default values for kibana.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image: docker.elastic.co/beats/metricbeat
imagePullPolicy: IfNotPresent

nameOverride: "metricbeat"
fullnameOverride: ""

resources:
  limits:
    memory: 512M
  requests:
    memory: 512M
