apiVersion: v1
kind: Service
metadata:
  name: {{ include "kibana.fullname" . }}
  labels:
{{ include "kibana.labels" . | indent 4 }}
spec:
  type: {{ .Values.serviceType }}
  ports:
    - port: {{ .Values.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "kibana.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
