apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "elastic.fullname" . }}
  labels:
{{ include "elastic.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "elastic.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
{{ include "elastic.labels" . | indent 8 }}
    spec:
      volumes:
      - name: esconfig
        configMap:
          name: {{ .Release.Name }}-config
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image }}:{{ .Values.imageTag }}"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        volumeMounts:
        - name: esconfig
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
          readOnly: true
        env:
        - name: ES_JAVA_OPTS
          value: .Values.esJavaOpts
        ports:
          - name: http
            containerPort: {{ .Values.httpPort }}
            protocol: TCP
        livenessProbe:
          httpGet:
            port: {{ .Values.httpPort }}
            path: /_cluster/health
          initialDelaySeconds: 300
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: {{ .Values.httpPort }}
          initialDelaySeconds: 60
          periodSeconds: 10
        resources:
          {{- toYaml .Values.resources | nindent 10 -}}
